name: dsc
description: A mobile app to help update and manage your DSC website easily

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.4
  provider: ^4.0.4
  font_awesome_flutter: ^8.7.0
  rflutter_alert: ^1.0.2
  progress_dialog: ^1.2.1
  google_fonts: ^0.3.9
  cloud_firestore: ^0.13.4+2
  flutter_svg: ^0.17.3+1
  url_launcher: ^5.4.2
  image_picker: any
  firebase_storage: any
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/icon_dark.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/json/
